In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First Matrix:\n",a)
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("\nSecond Matrix:\n",b)
print("\nSum of the matrices is")
c=a+b
print(c)

First Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Second Matrix:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

Sum of the matrices is
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [10]:
import numpy as np
a=np.array([[]])
b=np.array([[]])
r1=int(input("Enter the no. of rows of first matrix: "))
c1=int(input("Enter the no. of column of first matrix: "))
r2=int(input("Enter the no. of rows of second matrix: "))
c2=int(input("Enter the no. of column of second matrix: "))
for i in range(r1):
        a[i].append(list(map(int,input().split()))
for i in range(r2):
        b[i].append(list(map(int,input().split()))                
c=a+b
print(c)

SyntaxError: invalid syntax (<ipython-input-10-1f46ad6beac2>, line 10)